### ISSUE TITLE
Shootyrange map breaking delicounter

### ISSUE THREAD

**Issue by Watermelon4man** [Deli-Collective/DeliCounter.Database#108]
Delicounter does not load latest commits which breaks the shootyrange custommap.
![image](https://user-images.githubusercontent.com/53815775/123485203-e9c53f80-d609-11eb-9952-0d57504d2086.png)
The shootyrange custom map breaks Delicounter.
It's not inside a folder and It's not a  .JSON.
trying to fix it by making a folder called Shootyrange moving the file 1.5.0 and adding the .JSON. Creates the error displayed in the screenshot.
![image](https://user-images.githubusercontent.com/53815775/123484986-889d6c00-d609-11eb-9406-ddf7ab1a9ab5.png)

**Comment by nrgill28** [comment]
Authors field was a string and not an array of strings. It has been fixed.
