### ISSUE TITLE
Future-proofing ModulAR

### ISSUE THREAD

**Issue by Aegarain** [Deli-Collective/DeliCounter.Database#20]
When ModulAR was updated, modulPP became deprecated since it was part of moduAK v2. Meat has confirmed that they'll be giving a similar update to the ModulAR mods. What should we do with the old mods once the updates arrives? Mod Installer just edited the description of modulPP to say "Hey, this is obsolete, just download modulAK"

**Comment by nrgill28** [comment]
The mod can just be removed from the database, and I've already prepared for such a situation. An installed mod / mod version that is missing in the database will still allow you to uninstall said mod / mod version and once uninstalled it will disappear from the installer. (So if you have version 0.1 of a mod installed where only 0.2 is available in the database, updating will make version 0.1 disappear, and if an installed mod is completely removed from the database, the mod will still be listed in the installed mods page and still allow you to uninstall it before disappearing)
